alias md="mkdir"
alias c="clear"
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias sudo="sudo "
alias h="history"
alias j="jobs -l"
alias k="kill"
alias tm="tmux"
alias tma="tmux attach -d -t"
alias tms="tmux new -s"
alias tmk="tmux kill-set -t"
alias tml="tmux ls"
alias ss="ss -tulanp"
alias ps="ps aux"
alias x="exit"
alias e="ehco"
alias jctl="journalctl -xeu"
alias sctl="systemctl"

alias df="df -hT | { read -r line; echo "$line"; sort -k 7,7; }"

alias ll="ls -lh --group-directories-first"
alias la="ls -lah --group-directories-first"
alias ld="ls -lahd */"

alias grep="grep -n --color=auto"